### ISSUE TITLE
We need an Update to turn on tests for Spigot 1.19

### ISSUE THREAD

**Issue by CloudeLecaw** [KP56/Fake-Players-Spigot-Plugin#10]
On startup you just get

```
[22:41:51] [Server thread/ERROR]: Could not load 'plugins\FakePlayers_2.4.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.IllegalArgumentException: No enum constant me.KP56.FakePlayers.MultiVersion.Version.v1_17_R1
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:149) ~[server.jar:3124-Spigot-66f9d3c-384e116]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[server.jar:3124-Spigot-66f9d3c-384e116]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[server.jar:3124-Spigot-66f9d3c-384e116]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:384) ~[server.jar:3124-Spigot-66f9d3c-384e116]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:232) ~[server.jar:3124-Spigot-66f9d3c-384e116]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:986) ~[server.jar:3124-Spigot-66f9d3c-384e116]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[server.jar:3124-Spigot-66f9d3c-384e116]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.IllegalArgumentException: No enum constant me.KP56.FakePlayers.MultiVersion.Version.v1_17_R1
	at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
	at me.KP56.FakePlayers.MultiVersion.Version.valueOf(Version.java:3) ~[?:?]
	at me.KP56.FakePlayers.Main.<init>(Main.java:40) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:350) ~[?:?]
	at java.lang.Class.newInstance(Class.java:642) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:79) ~[server.jar:3124-Spigot-66f9d3c-384e116]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[server.jar:3124-Spigot-66f9d3c-384e116]
	... 7 more
```

**Comment by CloudeLecaw** [comment]
bump...for 1.19 now..

**Comment by CloudeLecaw** [comment]
well it looks like the update will not come anymore.. so i close the ticket for now
