### ISSUE TITLE
Issue when using with minecord and bots despawn on server restart

### ISSUE THREAD

**Issue by NFLD99** [KP56/Fake-Players-Spigot-Plugin#3]
hello, i get this spammed in console when i use your plugin with minecord, 

```
>.... [03:42:32 WARN]: [Minecord] Task #556 for Minecord v1.7.14_2 generated an exception
java.lang.NullPointerException: null
>.... [03:42:32 WARN]: [Minecord] Plugin Minecord v1.7.14_2 generated an exception while executing task 555
java.lang.NullPointerException: null
at me.spomg.minecord.chat.ChatScheduler.run(ChatScheduler.java:195) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-590]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-590]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-590]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_282]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_282]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
```

the bots also seem to despawn when the server restarts

**Comment by KP56** [comment]
Thank you for reporting this issue. I'll look into it.

**Comment by NFLD99** [comment]
Thank you, keep me posted, also have you thought of making a discord server?

**Comment by KP56** [comment]
I will think about it.

**Comment by KP56** [comment]
Two more questions:
- "restarting the server" you mean reloading?
- could you contact me on discord (KP56#9229) and send me a copy of a Minecord plugin, so I can check what player field is not instantiated properly?

**Comment by NFLD99** [comment]
"restarting the server" you mean reloading?
i mean killling and starting the server


could you contact me on discord (KP56#9229) and send me a copy of a Minecord plugin, so I can check what player field is not instantiated properly?
due to its a paid plugin i cant however i will contact you on discord after i get pad next to get you a copy of it

**Comment by KP56** [comment]
Don't worry about it then, I'll just contact the developer of Minecord. Bots disappearing after restarting the server is intended, but I can add a confing option to make them rejoin once that happens.

**Comment by NFLD99** [comment]
Sounds good, I've also contacted them aswell
