### ISSUE TITLE
Multiple errors on FakePlayers summon

### ISSUE THREAD

**Issue by SlimeDog** [KP56/Fake-Players-Spigot-Plugin#4]
Paper 1.16.5-610
FakePlayers 1.6 (the second one, md5=dd98d6dc6e569249baacc16826e2ffb1)
ForceResourcepacks 1.10.13-b489

The ForceResourcepacks pack still is not accepted. Despite that, FakePlayers reports that the fake player successfully summoned.
```
> fakeplayers summon BABYZ
[08:37:07 INFO]: [ViaVersionStatus] BABYZ is using version UNKNOWN(-1).
[08:37:07 INFO]: [pHD] Adding player BABYZ UUID 4420a7a8-aeaa-4b27-9c57-f3c2bc485d0d to cache
[08:37:07 INFO]: [on first join] set player's balance to 1000
[08:37:07 INFO]: [LP] Set blackdog.visited.world to true for BABYZ in context global.
[08:37:07 INFO]: [Thirst] Adding player BABYZ with thirst 100
[08:37:07 ERROR]: [Plan] Ran into NullPointerException - logged to plugins/Plan/logs/NullPointerException-9391cb41f5.txt
[08:37:07 ERROR]: [Plan] (INCLUDE CONTENTS OF THE FILE IN ANY REPORTS)
[08:37:07 ERROR]: [Plan] Error msg: "null"
[08:37:07 INFO]: [Disease] Loading player BABYZ
[08:37:07 INFO]: Fake Players » Successfully summoned a Fake Player.
[08:37:07 INFO]: [Essentials] Creating empty config: /home/ram/MC/plugins/Essentials/userdata/4420a7a8-aeaa-4b27-9c57-f3c2bc485d0d.yml
[08:37:07 INFO]: BABYZ lost connection: Sorry, you must enable the BlackDog resourcepacks
Edit the configuration for the server and try again
```
The subsequent errors are probably due to the fake player losing their connection.
Denizen 1.2.0-b5518
ItemJoin 5.2.2-b700
Plan 5.2-b1234
```
[08:37:07 FATAL]: Error executing task on Server
java.lang.NullPointerException: null
        at net.minecraft.server.v1_16_R3.NetworkManager.handleDisconnection(NetworkManager.java:529) ~[patched_1.16.5.jar:git-Paper-610]
        at com.denizenscript.denizen.nms.v1_16.impl.network.handlers.DenizenNetworkManagerImpl.handleDisconnection(DenizenNetworkManagerImpl.java:980) ~[?:?]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-610]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-610]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-610]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-610]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1262) ~[patched_1.16.5.jar:git-Paper-610]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1255) ~[patched_1.16.5.jar:git-Paper-610]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.5.jar:git-Paper-610]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1391) ~[patched_1.16.5.jar:git-Paper-610]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1126) ~[patched_1.16.5.jar:git-Paper-610]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-610]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[08:37:08 WARN]: [ItemJoin] Task #21890 for ItemJoin v5.2.2-SNAPSHOT-b700 generated an exception
java.lang.NullPointerException: null
        at me.RockinChaos.itemjoin.item.ItemUtilities.lambda$setInvSlots$5(ItemUtilities.java:593) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-610]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-610]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1423) ~[patched_1.16.5.jar:git-Paper-610]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.16.5.jar:git-Paper-610]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1338) ~[patched_1.16.5.jar:git-Paper-610]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1126) ~[patched_1.16.5.jar:git-Paper-610]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-610]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[08:37:08 WARN]: [ItemJoin] Task #21891 for ItemJoin v5.2.2-SNAPSHOT-b700 generated an exception
java.lang.NullPointerException: null
        at me.RockinChaos.itemjoin.item.ItemUtilities.lambda$setInvSlots$5(ItemUtilities.java:593) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-610]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-610]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1423) ~[patched_1.16.5.jar:git-Paper-610]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.16.5.jar:git-Paper-610]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1338) ~[patched_1.16.5.jar:git-Paper-610]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1126) ~[patched_1.16.5.jar:git-Paper-610]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-610]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[0
```

**Comment by KP56** [comment]
Which plugin do you use to detect player enabling their resource pack? I think the issue may be with sending an information to the server about accepting and downloading it before server sends fake player an information about it existing.

**Comment by SlimeDog** [comment]
The message (and kick)
```
[08:37:07 INFO]: BABYZ lost connection: Sorry, you must enable the BlackDog resourcepacks
Edit the configuration for the server and try again
```
is from `ForceResourcepacks` itself: `global.actions.declined`

**Comment by KP56** [comment]
Oh. Then I cannot cheat spigot the way I was trying to.

**Comment by KP56** [comment]
Ok thank you.

**Comment by SlimeDog** [comment]
```
Oh. Then I cannot cheat spigot the way I was trying to.
```
No. How did you test the code? You can use WorldResourcepacks (free version of same process).

**Comment by KP56** [comment]
At first I thought ForceResourcepacks is some sort of a spigot setting not a seperate plugin. I edited the message, when I realized my mistake.

**Comment by KP56** [comment]
> ```
> Oh. Then I cannot cheat spigot the way I was trying to.
> ```
> 
> No. How did you test the code? You can use WorldResourcepacks (free version of same process).

I coded my own plugin for that, but I guess other ones work differently.

**Comment by SlimeDog** [comment]
Please test with the plugin that is actually causing the problem. There is no reason to assume that you can duplicate its functionality, especially since it isn't open source.
